version: '3.8'
services:
  frontend_app:
    container_name: "starwars"
    image: "jaketracewell/starwarsreact"
    restart: "always"
    build: "."
    #port syntax= local port:app port
    ports:
      - "3000:3000"
    expose:
      - 3000